'use server';
/**
 * @fileOverview Professional Cabinet Architectural Extraction Flow.
 * Handles dual-page layouts (Drawing + Specs) and single-page data.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';
import * as fs from 'fs';
import * as path from 'path';

const LOG_FILE = path.join(process.cwd(), 'tmp_ai_scan_debug.log');
function logToFile(msg: string) {
  const timestamp = new Date().toISOString();
  try {
    fs.appendFileSync(LOG_FILE, `[${timestamp}] ${msg}\n`);
  } catch (e) {
    console.error('Logging failed:', e);
  }
}

const ItemSchema = z.object({
  code: z.string(),
  quantity: z.number(),
});

const RoomSchema = z.object({
  room_name: z.string(),
  cabinets: z.array(ItemSchema).optional().default([]),
  perimeter: z.array(ItemSchema).optional().default([]),
  island: z.array(ItemSchema).optional().default([]),
  hardware: z.array(ItemSchema).optional().default([]),
  bump: z.array(ItemSchema).optional().default([]),
  opt_crown: z.array(ItemSchema).optional().default([]),
  opt_light_rail: z.array(ItemSchema).optional().default([]),
  vent_chase_material: z.array(ItemSchema).optional().default([]),
});

const AnalyzeDrawingOutputSchema = z.object({
  rooms: z.array(RoomSchema),
});

export type AnalyzeDrawingOutput = z.infer<typeof AnalyzeDrawingOutputSchema>;

export async function analyzeDrawing(input: {
  pdfDataUri: string;
  projectName?: string;
}): Promise<AnalyzeDrawingOutput> {
  logToFile(`[SCAN START] Project: ${input.projectName || 'New Project'}`);

  try {
    const response = await ai.generate({
      model: 'googleai/gemini-3.1-flash-lite-preview', // Vision-optimized for fast scanning
      output: { schema: AnalyzeDrawingOutputSchema },
      prompt: [
        { media: { url: input.pdfDataUri, contentType: 'application/pdf' } },
        {
          text: `You are an expert cabinet estimator. Analyze the provided PDF drawing.
Your job is to visually identify and extract cabinet SKUs and accessory data directly from the drawings.

------------------------------------------------
VIRTUAL SCANNER RULES
1. Focus 100% on the VISUAL output of the blueprints.
2. Identify the room name from the drawing header, footer, or title block.
3. Extract every item (cabinets, hardware, fillers, etc.) into the "cabinets" list for that room.
4. Extract quantities (e.g., "3-BTK8" -> quantity 3, code BTK8). Default quantity to 1.

Return the final results as structured JSON.` }
      ],
      config: {
        temperature: 0,
      },
    });

    if (!response.output) {
      logToFile(`[SCAN ERROR] No output generated by AI.`);
      throw new Error('AI failed to generate results.');
    }

    logToFile(`[SCAN SUCCESS] Found ${response.output.rooms?.length || 0} rooms.`);
    logToFile(JSON.stringify(response.output, null, 2));

    return response.output;

  } catch (error: any) {
    logToFile(`[SCAN CRITICAL] ${error.message}`);
    if (error.stack) logToFile(error.stack);
    return { rooms: [] };
  }
}
